export enum SituationVol {
    EN_ATTENTE ="EN_ATTENTE",
    EN_PREPARATION = "EN_PREPARATION",
    EMBARQUEMENT = "EMBARQUEMENT",
    EN_VOL = "EN_VOL",
    ATTERRISSAGE = "ATTERRISSAGE",
    INCIDENT = "INCIDENT",
}
