export enum MoyenPayement {
    CHEQUE = "CHEQUE",
    VIREMENT = "VIREMENT",
    CARTE_BLEUE = "CARTE_BLEUE",
    ESPECE = "ESPECE",
    TICKET_RESTAURANT = "TICKET_RESTAURANT",
    REMBOURSEMENT = "REMBOURSEMENT"
}
